-- ============================================================
-- WBSL Lab Meeting - repair / migration
-- Supabase > SQL Editor에서 전체 붙여넣기 후 Run
-- 기존 랩미팅/논문/학생/Board 데이터는 삭제하지 않습니다.
-- ============================================================

-- 관리자 판별 함수 보장
create or replace function public.is_wbsl_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_wbsl_admin() from public;
grant execute on function public.is_wbsl_admin() to anon, authenticated;

-- 테이블 생성
create table if not exists public.lab_meetings (
  id bigint generated by default as identity primary key,
  meeting_date date not null,
  presenter text not null default '',
  category text not null default '연구 진행',
  title text not null,
  ppt_url text not null default '',
  pdf_url text not null default '',
  notes text not null default '',
  is_public boolean not null default true,
  sort_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 예전 버전 테이블이어도 필요한 컬럼 보완
alter table public.lab_meetings
  add column if not exists meeting_date date,
  add column if not exists presenter text not null default '',
  add column if not exists category text not null default '연구 진행',
  add column if not exists title text,
  add column if not exists ppt_url text not null default '',
  add column if not exists pdf_url text not null default '',
  add column if not exists notes text not null default '',
  add column if not exists is_public boolean not null default true,
  add column if not exists sort_order integer not null default 1,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table public.lab_meetings enable row level security;

-- 홈페이지 공개 자료 읽기
drop policy if exists "lab_meetings_public_read" on public.lab_meetings;
create policy "lab_meetings_public_read"
on public.lab_meetings for select
to anon, authenticated
using (is_public = true);

-- 관리자 전체 읽기
drop policy if exists "lab_meetings_admin_read" on public.lab_meetings;
create policy "lab_meetings_admin_read"
on public.lab_meetings for select
to authenticated
using (public.is_wbsl_admin());

-- 관리자 쓰기
drop policy if exists "lab_meetings_admin_insert" on public.lab_meetings;
create policy "lab_meetings_admin_insert"
on public.lab_meetings for insert
to authenticated
with check (public.is_wbsl_admin());

drop policy if exists "lab_meetings_admin_update" on public.lab_meetings;
create policy "lab_meetings_admin_update"
on public.lab_meetings for update
to authenticated
using (public.is_wbsl_admin())
with check (public.is_wbsl_admin());

drop policy if exists "lab_meetings_admin_delete" on public.lab_meetings;
create policy "lab_meetings_admin_delete"
on public.lab_meetings for delete
to authenticated
using (public.is_wbsl_admin());

-- 테이블 권한
grant usage on schema public to anon, authenticated;
grant select on public.lab_meetings to anon, authenticated;
grant insert, update, delete on public.lab_meetings to authenticated;

-- identity sequence 권한 (등록 실패 원인이 되는 경우가 있음)
do $$
declare
  seq_name text;
begin
  select pg_get_serial_sequence('public.lab_meetings', 'id') into seq_name;
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end $$;

-- 스키마 캐시가 새 구조를 다시 읽도록 요청
notify pgrst, 'reload schema';

-- 확인
select
  'lab_meetings ready' as status,
  count(*) as current_rows
from public.lab_meetings;
