-- ============================================================
-- WBSL Lab Meeting Archive
-- Supabase > SQL Editor에서 한 번만 실행하세요.
-- 기존 publications/news/members/slides 데이터는 변경하지 않습니다.
-- ============================================================

create table if not exists public.lab_meetings (
  id bigint generated by default as identity primary key,
  meeting_date date not null,
  presenter text not null default '',
  category text not null default '연구 진행',
  title text not null,
  ppt_url text not null default '',
  pdf_url text not null default '',
  notes text not null default '',
  is_public boolean not null default true,
  sort_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.lab_meetings enable row level security;

-- 홈페이지:
-- is_public = true 인 항목만 익명 방문자에게 공개됩니다.
drop policy if exists "lab_meetings_public_read" on public.lab_meetings;
create policy "lab_meetings_public_read"
on public.lab_meetings for select
to anon, authenticated
using (is_public = true);

-- 관리자:
-- admin_users에 등록된 로그인 계정은 공개/비공개 항목을 모두 읽을 수 있습니다.
drop policy if exists "lab_meetings_admin_read" on public.lab_meetings;
create policy "lab_meetings_admin_read"
on public.lab_meetings for select
to authenticated
using (public.is_wbsl_admin());

drop policy if exists "lab_meetings_admin_insert" on public.lab_meetings;
create policy "lab_meetings_admin_insert"
on public.lab_meetings for insert
to authenticated
with check (public.is_wbsl_admin());

drop policy if exists "lab_meetings_admin_update" on public.lab_meetings;
create policy "lab_meetings_admin_update"
on public.lab_meetings for update
to authenticated
using (public.is_wbsl_admin())
with check (public.is_wbsl_admin());

drop policy if exists "lab_meetings_admin_delete" on public.lab_meetings;
create policy "lab_meetings_admin_delete"
on public.lab_meetings for delete
to authenticated
using (public.is_wbsl_admin());

grant select on public.lab_meetings to anon, authenticated;
grant insert, update, delete on public.lab_meetings to authenticated;

-- ============================================================
-- 사용 방법
-- 1) Google Drive에 PPT/PDF 업로드
-- 2) 공유 권한 설정 (권장: 제한됨 + 랩원 이메일)
-- 3) 홈페이지 Admin > Lab Meeting에서 날짜/발표자/제목/Drive 링크 등록
-- ============================================================
