-- ============================================================
-- WBSL Website Admin - Supabase setup
-- Run this ONCE in Supabase > SQL Editor.
-- ============================================================

-- 1) Admin allow-list
create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

-- 2) Publications
create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  year integer not null,
  journal text not null default '',
  title text not null,
  authors text not null default '',
  url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3) News / Board
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  year integer not null,
  category text not null default 'News',
  title text not null,
  url text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4) Members
create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  english_name text not null default '',
  role text not null default '',
  group_name text not null default 'M.S. Students',
  research text not null default '',
  email text not null default '',
  photo_url text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 5) Home slider
create table if not exists public.slides (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  image_url text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Helper function: is the currently logged-in user an admin?
-- ------------------------------------------------------------
create or replace function public.is_wbsl_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_wbsl_admin() from public;
grant execute on function public.is_wbsl_admin() to anon, authenticated;

-- ------------------------------------------------------------
-- RLS
-- Public visitors can READ website content.
-- Only allow-listed authenticated admins can WRITE.
-- ------------------------------------------------------------
alter table public.admin_users enable row level security;
alter table public.publications enable row level security;
alter table public.news enable row level security;
alter table public.members enable row level security;
alter table public.slides enable row level security;

-- Admin list: a logged-in user may only see whether their own email is listed.
drop policy if exists "admin_users_read_self" on public.admin_users;
create policy "admin_users_read_self"
on public.admin_users for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- Publications
drop policy if exists "publications_public_read" on public.publications;
create policy "publications_public_read"
on public.publications for select
to anon, authenticated
using (true);

drop policy if exists "publications_admin_insert" on public.publications;
create policy "publications_admin_insert"
on public.publications for insert
to authenticated
with check (public.is_wbsl_admin());

drop policy if exists "publications_admin_update" on public.publications;
create policy "publications_admin_update"
on public.publications for update
to authenticated
using (public.is_wbsl_admin())
with check (public.is_wbsl_admin());

drop policy if exists "publications_admin_delete" on public.publications;
create policy "publications_admin_delete"
on public.publications for delete
to authenticated
using (public.is_wbsl_admin());

-- News
drop policy if exists "news_public_read" on public.news;
create policy "news_public_read"
on public.news for select
to anon, authenticated
using (true);

drop policy if exists "news_admin_insert" on public.news;
create policy "news_admin_insert"
on public.news for insert
to authenticated
with check (public.is_wbsl_admin());

drop policy if exists "news_admin_update" on public.news;
create policy "news_admin_update"
on public.news for update
to authenticated
using (public.is_wbsl_admin())
with check (public.is_wbsl_admin());

drop policy if exists "news_admin_delete" on public.news;
create policy "news_admin_delete"
on public.news for delete
to authenticated
using (public.is_wbsl_admin());

-- Members
drop policy if exists "members_public_read" on public.members;
create policy "members_public_read"
on public.members for select
to anon, authenticated
using (true);

drop policy if exists "members_admin_insert" on public.members;
create policy "members_admin_insert"
on public.members for insert
to authenticated
with check (public.is_wbsl_admin());

drop policy if exists "members_admin_update" on public.members;
create policy "members_admin_update"
on public.members for update
to authenticated
using (public.is_wbsl_admin())
with check (public.is_wbsl_admin());

drop policy if exists "members_admin_delete" on public.members;
create policy "members_admin_delete"
on public.members for delete
to authenticated
using (public.is_wbsl_admin());

-- Slides
drop policy if exists "slides_public_read" on public.slides;
create policy "slides_public_read"
on public.slides for select
to anon, authenticated
using (true);

drop policy if exists "slides_admin_insert" on public.slides;
create policy "slides_admin_insert"
on public.slides for insert
to authenticated
with check (public.is_wbsl_admin());

drop policy if exists "slides_admin_update" on public.slides;
create policy "slides_admin_update"
on public.slides for update
to authenticated
using (public.is_wbsl_admin())
with check (public.is_wbsl_admin());

drop policy if exists "slides_admin_delete" on public.slides;
create policy "slides_admin_delete"
on public.slides for delete
to authenticated
using (public.is_wbsl_admin());

-- ------------------------------------------------------------
-- Storage bucket for uploaded photos
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('wbsl-images', 'wbsl-images', true)
on conflict (id) do update set public = true;

-- Public image read
drop policy if exists "wbsl_images_public_read" on storage.objects;
create policy "wbsl_images_public_read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'wbsl-images');

-- Admin image upload
drop policy if exists "wbsl_images_admin_insert" on storage.objects;
create policy "wbsl_images_admin_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'wbsl-images' and public.is_wbsl_admin());

-- Admin image update
drop policy if exists "wbsl_images_admin_update" on storage.objects;
create policy "wbsl_images_admin_update"
on storage.objects for update
to authenticated
using (bucket_id = 'wbsl-images' and public.is_wbsl_admin())
with check (bucket_id = 'wbsl-images' and public.is_wbsl_admin());

-- Admin image delete
drop policy if exists "wbsl_images_admin_delete" on storage.objects;
create policy "wbsl_images_admin_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'wbsl-images' and public.is_wbsl_admin());

-- ============================================================
-- AFTER running this file:
-- 1. Supabase > Authentication > Users > create your admin user.
-- 2. Run the line below after replacing the email:
--
-- insert into public.admin_users(email)
-- values ('YOUR_ADMIN_EMAIL@example.com')
-- on conflict (email) do nothing;
--
-- Do NOT put a service_role/secret key in GitHub Pages.
-- ============================================================
